#WARNING: This file is automatically overwritten every time you close a project. 
#         Add any startup commands to maestro.cmd
#         ** Do NOT edit this file! **
projectprefer feedbackproperty="Title"
projectprefer feedbackproperties="s_m_title s_pdb_PDB_ID r_i_docking_score"
projectprefer phasefeedbackproperties=""
projectprefer show2dstructures=false
projectprefer starsonright=true
projectprefer 2dstructureheight=200
projectprefer 2dstructurewidth=300
entryexport selected_properties=""
entryexportspreadsheet selected_properties=""
projectprefer entrylistvisiblesubset="s_m_title r_psp_IFDScore "
projectprefer entrylistcolumnwidths="53 8"
projectprefer showentrylist2dstructures=false
projectprefer entrylist2dstructureheight=75
projectprefer entrylist2dstructurewidth=75
projectprefer showentryliststars=false
projectprefer enotationproperties=""
projectprefer muterowcolumncolors=false
